"""initial

Revision ID: 3c2cfcc416f4
Revises: 
Create Date: 2026-04-01 19:43:13.610975
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c2cfcc416f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_username'), 'agents', ['username'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('visitor_name', sa.Text(), nullable=False),
    sa.Column('visitor_phone', sa.Text(), nullable=True),
    sa.Column('visitor_org', sa.Text(), nullable=True),
    sa.Column('initial_message', sa.Text(), nullable=False),
    sa.Column('visitor_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_sessions_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_created', 'chat_sessions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_sessions_status', 'chat_sessions', ['status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_chat_sessions_visitor_token'), 'chat_sessions', ['visitor_token'], unique=True)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_attempts_ip', 'login_attempts', ['ip_address', 'attempted_at'], unique=False)
    op.create_table('widget_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('header_title', sa.String(length=100), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('auto_close_minutes', sa.Integer(), nullable=False),
    sa.Column('telegram_bot_token', sa.String(length=255), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('allowed_file_types', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=False),
    sa.Column('privacy_policy_url', sa.String(length=500), nullable=True),
    sa.Column('form_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_origins', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('admin_ip_whitelist', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('smartcaptcha_key', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_widget_settings_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_messages_unread', 'messages', ['session_id', 'is_read'], unique=False, postgresql_where='is_read = false')
    op.create_table('session_notes',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_session', 'session_notes', ['session_id'], unique=False)
    op.create_table('attachments',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attachments_message', 'attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_attachments_message', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('idx_notes_session', table_name='session_notes')
    op.drop_table('session_notes')
    op.drop_index('idx_messages_unread', table_name='messages', postgresql_where='is_read = false')
    op.drop_index('idx_messages_session', table_name='messages')
    op.drop_table('messages')
    op.drop_table('widget_settings')
    op.drop_index('idx_login_attempts_ip', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_chat_sessions_visitor_token'), table_name='chat_sessions')
    op.drop_index('idx_sessions_status', table_name='chat_sessions', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_sessions_created', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_agents_username'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
